# Generated by Django 4.2.9 on 2024-03-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="", max_length=8, unique=True)),
                ("host", models.CharField(max_length=55, unique=True)),
                ("votes_to_skip", models.IntegerField(default=1)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
